package com.example.data

import android.util.Base64
import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiApiClient {
    private const val TAG = "GeminiApiClient"
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val mediaTypeJson = "application/json; charset=utf-8".toMediaType()

    /**
     * Generates a text response from the Gemini 3.5 Flash model.
     * Supports optional system instructions and Google Search Grounding.
     */
    suspend fun generateContent(
        prompt: String,
        systemInstruction: String? = null,
        useSearch: Boolean = false
    ): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            Log.e(TAG, "API Key is missing or default placeholder.")
            return@withContext "Error: Gemini API Key is not set. Please add it to your AI Studio Secrets panel."
        }

        val url = "$BASE_URL/gemini-3.5-flash:generateContent?key=$apiKey"

        try {
            // Build contents payload
            val contentsArray = JSONArray().apply {
                val partsArray = JSONArray().apply {
                    put(JSONObject().apply { put("text", prompt) })
                }
                put(JSONObject().apply { put("parts", partsArray) })
            }

            val requestJson = JSONObject().apply {
                put("contents", contentsArray)

                if (systemInstruction != null) {
                    val systemParts = JSONArray().apply {
                        put(JSONObject().apply { put("text", systemInstruction) })
                    }
                    put("systemInstruction", JSONObject().apply { put("parts", systemParts) })
                }

                if (useSearch) {
                    val toolsArray = JSONArray().apply {
                        put(JSONObject().apply {
                            put("googleSearch", JSONObject())
                        })
                    }
                    put("tools", toolsArray)
                }
            }

            val body = requestJson.toString().toRequestBody(mediaTypeJson)
            val request = Request.Builder()
                .url(url)
                .post(body)
                .build()

            client.newCall(request).execute().use { response ->
                val bodyString = response.body?.string() ?: ""
                if (!response.isSuccessful) {
                    Log.e(TAG, "Unsuccessful response: ${response.code} - $bodyString")
                    return@withContext "Error: Failed to fetch insights from AI (HTTP ${response.code})."
                }

                try {
                    val jsonResponse = JSONObject(bodyString)
                    val candidates = jsonResponse.getJSONArray("candidates")
                    if (candidates.length() > 0) {
                        val firstCandidate = candidates.getJSONObject(0)
                        val content = firstCandidate.getJSONObject("content")
                        val parts = content.getJSONArray("parts")
                        if (parts.length() > 0) {
                            val text = parts.getJSONObject(0).getString("text")
                            return@withContext text
                        }
                    }
                    return@withContext "Error: No insights generated by the model."
                } catch (e: Exception) {
                    Log.e(TAG, "Error parsing JSON response: ${e.message}")
                    return@withContext "Error: Failed to process AI response."
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Network error: ${e.message}", e)
            return@withContext "Error: Network communication failure. Please check your connection."
        }
    }

    /**
     * Generates a TTS audio payload from the Gemini 3.1 Flash TTS model.
     * Returns a Base64-decoded byte array of the audio.
     */
    suspend fun generateSpeech(text: String): ByteArray? = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            Log.e(TAG, "API Key is missing or default placeholder.")
            return@withContext null
        }

        val url = "$BASE_URL/gemini-3.1-flash-tts-preview:generateContent?key=$apiKey"

        try {
            val contentsArray = JSONArray().apply {
                val partsArray = JSONArray().apply {
                    put(JSONObject().apply { put("text", text) })
                }
                put(JSONObject().apply { put("parts", partsArray) })
            }

            val requestJson = JSONObject().apply {
                put("contents", contentsArray)

                val genConfig = JSONObject().apply {
                    val responseModalities = JSONArray().apply {
                        put("AUDIO")
                    }
                    put("responseModalities", responseModalities)

                    val speechConfig = JSONObject().apply {
                        val voiceConfig = JSONObject().apply {
                            val prebuiltVoiceConfig = JSONObject().apply {
                                put("voiceName", "Kore") // Warm male/female hybrid voice
                            }
                            put("prebuiltVoiceConfig", prebuiltVoiceConfig)
                        }
                        put("voiceConfig", voiceConfig)
                    }
                    put("speechConfig", speechConfig)
                }
                put("generationConfig", genConfig)
            }

            val body = requestJson.toString().toRequestBody(mediaTypeJson)
            val request = Request.Builder()
                .url(url)
                .post(body)
                .build()

            client.newCall(request).execute().use { response ->
                val bodyString = response.body?.string() ?: ""
                if (!response.isSuccessful) {
                    Log.e(TAG, "Unsuccessful TTS response: ${response.code} - $bodyString")
                    return@withContext null
                }

                try {
                    val jsonResponse = JSONObject(bodyString)
                    val candidates = jsonResponse.getJSONArray("candidates")
                    if (candidates.length() > 0) {
                        val firstCandidate = candidates.getJSONObject(0)
                        val content = firstCandidate.getJSONObject("content")
                        val parts = content.getJSONArray("parts")
                        if (parts.length() > 0) {
                            val part = parts.getJSONObject(0)
                            if (part.has("inlineData")) {
                                val inlineData = part.getJSONObject("inlineData")
                                val base64Data = inlineData.getString("data")
                                return@withContext Base64.decode(base64Data, Base64.DEFAULT)
                            }
                        }
                    }
                    return@withContext null
                } catch (e: Exception) {
                    Log.e(TAG, "Error parsing TTS JSON response: ${e.message}")
                    return@withContext null
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Network error during TTS: ${e.message}", e)
            return@withContext null
        }
    }
}
